spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
  data:
    web:
      pageable:
#        default-page-size: 10
        max-page-size: 2000
#        one-indexed-parameters: true      파라미터 page 숫자를 -1 시켜서 페이지 목록을 보여줌(ex) page=1을 넣을 경우 -1 시켜서 0페이지 내용을 보여줌)


logging:
  level:
    org.hibernate.SQL: debug  # logger를 통해 하이버네이트 실행 SQL을 남긴다
#    org.hibernate.type: trace
