spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/simpleboard
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  servlet:
    context-path: /

logging:
  level:
    org.hibernate.SQL: debug
